# Workflow to perform testings and code coverage.
#
# To run this check locally from the `doc` folder:
#
# .. code-block:: bash
#
#   $ nosetests --with-coverage --cover-package=hopla --verbosity=2
#     --with-doctest --doctest-options='+ELLIPSIS,+NORMALIZE_WHITESPACE'
###
name: "Testing[nosetests]"

on:
  push:
    branches:
      - "master"
      - "main"
      - "dev"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy
        python -m pip install pynose coverage[toml]
        python -m pip install --progress-bar off .
    - name: Run unit tests
      run: |
        nosetests --with-coverage --cover-package=hopla --verbosity=2 --with-doctest --doctest-options='+ELLIPSIS,+NORMALIZE_WHITESPACE'
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        debug: true
        fail-on-error: true
